### ISSUE TITLE
Can't serialize/deserialize a sparse matrix using UInt40 (bug?)

### ISSUE THREAD

**Issue by lesshaste** [rfourquet/BitIntegers.jl#15]
This is a copy of the report at: https://discourse.julialang.org/t/cant-serialize-deserialize-a-sparse-matrix-using-uint40-bug/39456

Take this simple code:

```
using Serialization
using BitIntegers
using SparseArrays
BitIntegers.@define_integers 40
M = spzeros(UInt8, UInt40, 10, 10)
M[2,2] = 4
serialize("test.jls", M)
```

I then open a different Julia REPL and run:

```
using Serialization
using BitIntegers
using SparseArrays
BitIntegers.@define_integers 40
deserialize("test.jls")
```

I get:

> 10×10 SparseMatrixCSC{UInt8,UInt40} with 799661643759 stored entries:Error showing value of type SparseMatrixCSC{UInt8,UInt40}:
> ERROR: BoundsError: attempt to access 1-element Array{UInt40,1} at index [1:9]
> Stacktrace:
>  [1] throw_boundserror(::Array{UInt40,1}, ::Tuple{UnitRange{Int64}}) at ./abstractarray.jl:537
>  [2] checkbounds at ./abstractarray.jl:502 [inlined]
>  [3] getindex(::Array{UInt40,1}, ::UnitRange{Int64}) at ./array.jl:794
>  [4] show(::IOContext{REPL.Terminals.TTYTerminal}, ::SparseMatrixCSC{UInt8,UInt40}) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/SparseArrays/src/sparsematrix.jl:240
>  [5] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::SparseMatrixCSC{UInt8,UInt40}) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/SparseArrays/src/sparsematrix.jl:197
>  [6] display(::REPL.REPLDisplay, ::MIME{Symbol("text/plain")}, ::Any) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/REPL/src/REPL.jl:137
>  [7] display(::REPL.REPLDisplay, ::Any) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/REPL/src/REPL.jl:141
>  [8] display(::Any) at ./multimedia.jl:323
>  [9] #invokelatest#1 at ./essentials.jl:712 [inlined]
>  [10] invokelatest at ./essentials.jl:711 [inlined]
>  [11] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/REPL/src/REPL.jl:161
>  [12] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/REPL/src/REPL.jl:146
>  [13] (::REPL.var"#do_respond#38"{Bool,REPL.var"#48#57"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/REPL/src/REPL.jl:729
>  [14] #invokelatest#1 at ./essentials.jl:712 [inlined]
>  [15] invokelatest at ./essentials.jl:711 [inlined]
>  [16] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2354
>  [17] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/REPL/src/REPL.jl:1055
>  [18] run_repl(::REPL.AbstractREPL, ::Any) at /home/user/bin/julia-1.4.1/share/julia/stdlib/v1.4/REPL/src/REPL.jl:206
>  [19] (::Base.var"#764#766"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:383
>  [20] #invokelatest#1 at ./essentials.jl:712 [inlined]
>  [21] invokelatest at ./essentials.jl:711 [inlined]
>  [22] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:367
>  [23] exec_options(::Base.JLOptions) at ./client.jl:305
>  [24] _start() at ./client.jl:484

Is this a bug?

**Comment by rfourquet** [comment]
> Is this a bug?

I would say it's a missing feature:
```julia
julia> serialize(io, UInt256(1))
ERROR: MethodError: no method matching write(::Base.GenericIOBuffer{Array{UInt8,1}}, ::UInt256)
[...]
```
So specializing `write` and/or maybe a couple other methods seems to be required for `serialize`.

**Comment by lesshaste** [comment]
If it's not a pain, it would be really great if this could be fixed (please).
