### ISSUE TITLE
UInt24 : cannot convert to/from big endian format

### ISSUE THREAD

**Issue by tk3369** [rfourquet/BitIntegers.jl#23]
Hi, this is a great package! Thanks.

I'm trying to use this for a project that requires UInt24. Because I have to handle big endian, I normally just call `ntoh`  and `hton` when reading/writing such data. However:

```julia
julia> BitIntegers.@define_integers 24
@uint24_str (macro with 1 method)

julia> UInt24(0x010203)
0x010203

julia> hton(UInt24(0x010203))
ERROR: unimplemented
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] bswap(x::UInt24)
   @ BitIntegers ~/.julia/dev/BitIntegers/src/BitIntegers.jl:356
 [3] hton(x::UInt24)
   @ Base ./io.jl:568
```

**Comment by tk3369** [comment]
If I replace the `bswap` function with:
```julia
function bswap(x::XBI)
    return bswap_int(x)
end
```

Then it seems to work correctly.
```julia
julia> hton(UInt24(0x010203))
0x030201
```

The comment says LLVM instruction is invalid though...
https://github.com/rfourquet/BitIntegers.jl/blob/c9a3e7e4d3b3221cad3a9864675545273154bbe9/src/BitIntegers.jl#L353-L360

**Comment by rfourquet** [comment]
Thanks for your issue! It indeed works now. Up until julia v1.5, it was segfaulting (at least on my machine). I will enable this function on 1.6+.
