### ISSUE TITLE
BitIntegers with julia 1.6

### ISSUE THREAD

**Issue by LinjianMa** [rfourquet/BitIntegers.jl#25]
Hi! 

It seems for now BitIntegers doesn't support Julia 1.6. May I ask is it possible to let the package support Julia 1.6? Thank you!

**Comment by rfourquet** [comment]
What gives you the impression that Julia 1.6 is not supported?

**Comment by LinjianMa** [comment]
I'm so sorry that there's something wrong with my own setup, BitIntegers works fine. I will close the issue
