### ISSUE TITLE
Currently fails to precompile at Julia nightly

### ISSUE THREAD

**Issue by zsoerenm** [rfourquet/BitIntegers.jl#29]
I'm not sure if this is a problem of Julia or this module.
BitIntegers currently fails to pre-compile at Julia nightly:
https://github.com/JuliaGNSS/GNSSDecoder.jl/actions/runs/3530854086/jobs/5923318476

**Comment by rfourquet** [comment]
This presumably comes from  https://github.com/JuliaLang/julia/pull/47567.

**Comment by rfourquet** [comment]
This seems to be fixed.
