### ISSUE TITLE
Testing triggers LLVM assertion

### ISSUE THREAD

**Issue by maleadt** [rfourquet/BitIntegers.jl#39]
PkgEval tests with Julia and LLVM assertions enabled now, triggering e.g. in https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-07/22/BitIntegers.primary.log:

```
bswap must be an even number of bytes
  %5 = call i24 @llvm.bswap.i24(i24 %"x::UInt24"), !dbg !16
```

This makes BitIntegers.jl sit at the top of every daily PgkEval report now, so would be good to fix 🙂

**Comment by rfourquet** [comment]
> This makes BitIntegers.jl sit at the top of every daily PgkEval report now

Sorry for this! this should hopelly be fixed now, assuming this issue is the same as #38. Please reopen if this failure appears again.
