### ISSUE TITLE
powermod(::UInt,...) returns wrong value

### ISSUE THREAD

**Issue by roshii** [rfourquet/BitIntegers.jl#4]
If I'm not mistaking the below should return true but does not.

```
p = rand(UInt256)
n = rand(0:p)
P = big(p)
N = big(n)
powermod(N,P-0x02,P) == big(powermod(n,p-0x02,p))
```

**Comment by rfourquet** [comment]
It returns `true` for me, with few different values... Do you have specific values for which this fails?

**Comment by roshii** [comment]
Well, it works indeed...
While editing the issue I realize I had made a typo in my test which I wasn't aable to retest at that time.
Test aside, I realize the error in my code came from a coefficient applied to the result of powermod, going outside of UInt256 boundaries.

Thanks for checking and another one for the package :)
